name: E2E Tests

on:
  pull_request:
    branches:
      - main
      - development
  push:
    branches:
      - main
      - development

jobs:
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start backend stack
        working-directory: infra
        run: docker-compose up -d

      - name: Wait for API healthcheck
        run: |
          timeout 60 bash -c 'until curl -sSf http://localhost:8080/health >/dev/null; do sleep 2; done'

      - name: Run Playwright tests
        run: npm run test:e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report
          retention-days: 7

      - name: Upload JUnit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-junit
          path: frontend/test-results/junit.xml
          retention-days: 7

      - name: Shutdown backend stack
        if: always()
        working-directory: infra
        run: docker-compose down
