name: Frontend CI

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/pr-frontend.yml'
  push:
    branches:
      - development
    paths:
      - 'frontend/**'
      - '.github/workflows/pr-frontend.yml'

jobs:
  test:
    name: Test Frontend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
        
      - name: Run ESLint
        working-directory: frontend
        run: npm run lint
        
      - name: Run TypeScript checks
        working-directory: frontend
        run: npm run typecheck
        
      - name: Run tests
        working-directory: frontend
        run: npm run test:coverage
        
      - name: Build application
        working-directory: frontend
        run: npm run build

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage/